### ISSUE TITLE
ICACHE_RAM_ATTR needed

### ISSUE THREAD

**Issue by alka79** [Erriez/ErriezRotaryEncoderFullStep#3]
Hello,
I have tried several encoder libraries with interrupts on ESP8266  : yours is the only one really working :) Thanks for sharing.
It is fast, accurate and simple. The speed idea is great.
I use it with NodeMCU ESP8266 and KY-40 encoder, with 100nf capacitors to help debounce.

One issue though : recent versions of Arduino ESP8266 Core require to add the ICACHE_RAM_ATTR macro for ISR functions. Otherwise, the code compiles but crashes. 
The fix is quite simple in your examples : `void ICACHE_RAM_ATTR rotaryInterrupt()`
It is a good practice.
Al

**Comment by Erriez** [comment]
Thanks for your feedback. I had the same problem to find a reliable rotary library, so I developed it myself by combining several other projects. Please notice that I've two libraries: A full step and half step. The encoding is different and does not work when the wrong one is used.

I also noticed the `ICACHE_RAM_ATTR` for the ESP8266 and ESP32 interrupt service routines. Yes, it compiles but crashes.

At the moment I've no hardware to test this, but prepared a fix for you in `InterruptFullStepBasic.ino`:

```
#if defined(ARDUINO_ARCH_ESP8266) || defined(ARDUINO_ARCH_ESP32)
ICACHE_RAM_ATTR
#endif
void rotaryInterrupt()
```
Can you test the change in the example above and let me know if this works? Then I'll update the other examples with the same construction.

Note: Macro's in examples are not preferred by the Arduino group, but I don't want to create copies of the examples.

**Comment by alka79** [comment]
I just tested the below code : it works on my ESP8266 NodeMCU board

Al

Le 01/07/2020 à 22:48, Erriez a écrit :

**Comment by Erriez** [comment]
I apologize for my late response. I'm refactoring and fixing my libraries and included this fix.
