### ISSUE TITLE
ATSAMD21

### ISSUE THREAD

**Issue by koogar** [Erriez/ErriezRotaryEncoderFullStep#4]
Hi Erriez,

Thanks for your encoder library, nice documentation also.

Have you done any work on ATSAMD support?

Regards

Rupert

**Comment by Erriez** [comment]
Hi @koogar,

Thanks for your request. I did not test the ATSAMD family as I do not have such processor. I do not expect platform specific differences as the library uses common API calls. 

I tried to build the full step interrupt example for a `Arduino M0` board and give an error:

```
D:\Arduino\libraries\ErriezRotaryEncoderFullStep\src\ErriezRotaryFullStep.cpp:36:10: fatal error: pgmspace.h: No such file or directory
 #include <pgmspace.h>
          ^~~~~~~~~~~~
compilation terminated.
```

This can be solved by changing the code below in `ErriezRotaryEncoderFullStep\src\ErriezRotaryFullStep.cpp`:

```c++
#if defined(__AVR__) || defined(ARDUINO_ARCH_SAMD)
#include <avr/pgmspace.h>
#else
#include <pgmspace.h>
#endif
```

Can you give it a try?

Thanks,
Erriez

**Comment by Erriez** [comment]
@koogar Did you try this library on your ATSAMD target?

**Comment by koogar** [comment]
Hi Erriez,

Sorry for the late reply I have only just had time to try it.
yes it did work, thanks for your time

**Comment by koogar** [comment]
Hi Erriez,

I also have it  working on a  SMT32F1 by changing the .CPP, 

`#if (defined(__SAM3X8E__) || defined(__STM32F1__)) ` 

to combine the ATSAMD and the STM32 would this be the correct way of doing it in the .CPP

```
#if ((defined(__AVR__) || defined(ARDUINO_ARCH_SAMD)) or (__SAM3X8E__) || defined(__STM32F1__))
#include <avr/pgmspace.h>
#else
#include <pgmspace.h>
#endif
```

Cheers

Rupert

**Comment by Erriez** [comment]
@koogar Thanks for your feedback and patient. I've created a new release with SAMD21 and STM32F1 support.
